Stm32 add cmake
AlbaSat/OBC pull request #10
Opened 2023-12-06 08:04 UTC by BIRSAx2

2023-12-07 16:15 UTC, safesintesi commented on README.md
> +```shell
Either change bash in the first line of the README.md or change shell here and at line 36.

2023-12-07 16:17 UTC, safesintesi commented on README.md
> +mkdir -p build
It's not an error, but -p is useless in this line. Someone might ask why we put it here.

2023-12-07 16:18 UTC, safesintesi commented on README.md
> +Please note that the `cmake ..` might take a while to complete the first time.g
Yoooo the g at the end is a real G.

2023-12-07 16:20 UTC, safesintesi commented on README.md
> +- Install the ST-Link utility from [here](https://github.com/stlink-org/stlink).
Usually dependencies are put before the building procedure. It's a pain when you have almost done everything and discover that you have to install other stuff.

2023-12-07 16:33 UTC, safesintesi commented on CMakeLists.txt
> +set(CMAKE_C_FLAGS "${COMMON_FLAGS} -Wall -fdata-sections -ffunction-sections ${CMAKE_C_FLAGS}")
You set a C++ compiler and a C++ standard, at this point set also its flags (CMAKE_CXX_FLAGS).

2023-12-07 16:41 UTC, safesintesi commented on CMakeLists.txt
> +set(FREERTOS_HEAP "4" CACHE STRING "" FORCE)
We are using heap 3

2023-12-07 16:45 UTC, safesintesi commented on CMakeLists.txt
> +        GIT_TAG 086960fd749b638afd0985ec94e183281319c4c2 #Note: Best practice to use specific git-hash or tagged version
We are currently using 25129e5221ae6ebf9d88e11f78d33c68edb254fb as submodule.
Either this or the submodule needs to change.

2023-12-07 16:47 UTC, safesintesi commented on CMakeLists.txt
> +        GIT_TAG V10.6.2 #Note: Best practice to use specific git-hash or tagged version
We can keep 10.6.2 as tag, but we need to update the submodule then.

2023-12-07 17:26 UTC, BIRSAx2 commented on CMakeLists.txt
> +        GIT_TAG V10.6.2 #Note: Best practice to use specific git-hash or tagged version
Okay, go ahead an update the submodule

2023-12-07 17:28 UTC, BIRSAx2 commented on CMakeLists.txt
> +        GIT_TAG 086960fd749b638afd0985ec94e183281319c4c2 #Note: Best practice to use specific git-hash or tagged version
Okay, I'll change the one on the CMakeLists.txt

2023-12-07 17:30 UTC, BIRSAx2 commented on Core/Inc/task1_ale.h
It might be outdated; as far as I know, that task never compiled in the first place

2023-12-09 19:41 UTC, BIRSAx2 commented
@safesintesi  Any blockers preventing the merge of this pull request? If not, could you please provide some insights into the delay?

2023-12-09 20:13 UTC, safesintesi requested changes
Modify cmake dependency

2023-12-09 20:13 UTC, safesintesi commented on README.md
> +- CMake 3.10 or higher
FetchContent is cmake 3.11

2023-12-09 20:20 UTC, safesintesi approved these changes

2023-12-09 20:21 UTC, merged